### ISSUE TITLE
command-not-found 更新到23.04后，sudo apt update 报错

### ISSUE THREAD

**Issue by ice909** [deepin-community/command-not-found#3]
```bash
ice@ice-PC:~$ sudo apt update
命中:2 https://community-packages.deepin.com/driver-23 driver InRelease                                      
命中:1 https://community-packages.deepin.com/beige beige InRelease                                           
命中:3 https://app-store-files.uniontech.com/241012134226584/appstorev23 beige InRelease                     
命中:4 https://packages.element.io/debian default InRelease                                                  
命中:5 https://proposed-packages.deepin.com/beige-testing unstable InRelease
Traceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 32, in <module>
    col.create(db)
  File "/usr/share/command-not-found/CommandNotFound/db/creator.py", line 96, in create
    self._fill_commands(con)
  File "/usr/share/command-not-found/CommandNotFound/db/creator.py", line 141, in _fill_commands
    self._parse_single_contents_file(con, f, sub.stdout)
  File "/usr/share/command-not-found/CommandNotFound/db/creator.py", line 241, in _parse_single_contents_file
    l = l.decode("utf-8")
        ^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 48: invalid start byte
正在读取软件包列表... 完成
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code

```

**Comment by ice909** [comment]
@xzl01 不知道是不是这个包的问题

**Comment by UTsweetyfish** [comment]
这个是因为有一个文件是非 utf-8 的编码，没记错的话已经解决了。
